#!/usr/bin/env bash

#===================================================================================================
#
#  Author:				Christian Zettel (ccztux)
#						2017-02-04
#						http://linuxinside.at
#
#  Copyright:			Copyright © 2017 Christian Zettel (ccztux), all rights reserved
#
#  Project website:		https://github.com/ccztux/glsysbackup
#
#  Last Modification:	Christian Zettel (ccztux)
#						2019-11-23
#
#  Version				2.0.0-rc1
#
#  Description:			Generic Linux System Backup is an advanced backup tool written in bash.
#
#  License:				GNU GPLv3
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===================================================================================================


#-----------
# Functions:
#-----------

makeAutomysqlbackup()
{
	local rc="0"
	local file=
	local CONFIG_backup_dir=
	local conf_dir="/etc/automysqlbackup/conf.d/"

	printf "Starting automysqlbackup...\\n"

	for file in "${conf_dir}*.conf"
	do
		if [ -f "${file}" ] && [ -s "${file}" ]
		then
			source "${file}"
		else
			continue
		fi

		if [ ! -d "${CONFIG_backup_dir}" ]
		then
			mkdir -p "${CONFIG_backup_dir}"
		fi

		if ! /usr/local/bin/automysqlbackup -b -c "${file}"
		then
			rc="1"
		fi

		#chown -R root:root ${CONFIG_backup_dir}*
		#find ${CONFIG_backup_dir}* -type f -exec chmod 600 {} \;
		#find ${CONFIG_backup_dir}* -type d -exec chmod 700 {} \;
	done

	return "${rc}"
}



#-------
# Start:
#-------

if makeAutomysqlbackup
then
	printf "automysqlbackup was successful...\\n"
	exit 0
else
	printf "automysqlbackup was NOT successful...\\n"
	exit 1
fi
