name: Differential ShellCheck
on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@latest
        with:
          shell-scripts:
            /usr/local/glsysbackup/bin/glsysbackup
            /usr/local/glsysbackup/libexec/create_automysqlbackup
            /usr/local/glsysbackup/libexec/scp_to_remote_host
          token: ${{ secrets.GITHUB_TOKEN }}
