name: ShellCheck
on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Show versions
        run: |
          bash --version
          shellcheck --version

      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Shellcheck
        run: |
          shellcheck --color=always --check-sourced --external-sources ./usr/local/glsysbackup/bin/glsysbackup
          shellcheck --color=always ./usr/local/glsysbackup/libexec/create_automysqlbackup
          shellcheck --color=always ./usr/local/glsysbackup/libexec/scp_to_remote_host
        working-directory: ./
